export const ADVERT_LIST_REQUEST = 'ADVERT_LIST_REQUEST'
export const ADVERT_LIST_SUCCESS = 'ADVERT_LIST_SUCCESS'
export const ADVERT_LIST_FAIL = 'ADVERT_LIST_FAIL'

export const ADVERT_DETAILS_REQUEST = 'ADVERT_DETAILS_REQUEST'
export const ADVERT_DETAILS_SUCCESS = 'ADVERT_DETAILS_SUCCESS'
export const ADVERT_DETAILS_FAIL = 'ADVERT_DETAILS_FAIL'

